### ISSUE TITLE
Lucee 4.5 Extension Provider Error

### ISSUE THREAD

**Issue by jamiejackson** [Leftbower/cfspreadsheet-lucee#4]
I'm trying to install in Lucee 4.5.5.006 using `http://cfspreadsheet.leftbower.com/ExtensionProvider.cfc` as the provider. However "verify" shows `Error` in the `check` column, and the provider doesn't show up in "Extension - Applications."

**Comment by Leftbower** [comment]
That is indeed odd. The code for the 4.x extension has not been touched in about a year and the site is up and running fine? I use Lucee 5.x exclusively so I have not bothered to check back on this extension for some time. I will need to see if any recent updates to Lucee 4.x changed something with the way extensions are reached.

In the meantime, have you tried installing it manually?

**Comment by Leftbower** [comment]
ok, it's a hack, but I added query column datatypes and changed it from `Timespan` to `Date` and I changed the `CreateDate(2016,6,18)` to just a string representation of today's date. I cannot control the serialization by Lucee, so this is the best I can do to get it back up online.

**Comment by jamiejackson** [comment]
Seems like a decent hack. I've been tied up today, but I just got a chance to try it. (I'm using CommandBox.)

The ExtensionProvider got added fine, but I think I got a timeout when installing the extension:

```
Lucee 4.5.2.018 Error (application)
Message	can't copy file [http://cfspreadsheet.leftbower.com:80/cfpoi.zip] to [/Users/jjackson/.CommandBox/server/87378098F0782EC1E8CA5FB73719A7A7-cb/lucee-4.5.2.018/WEB-INF/lucee-web/extensions/4C901E6B63FD9B49107D97B6E2C67D33/4.1.1.rep]
Detail	Read timed out
Stacktrace	The Error Occurred in
/lucee-context-compiled/admin/extension/ExtensionManager.cfc: line 167 
called from /lucee-context-compiled/admin/extension.applications.install1.cfm: line 47 
called from /lucee-context-compiled/admin/extension.applications.cfm: line 98 
called from /lucee-context-compiled/admin/web.cfm: line 389 
Java Stacktrace	can't copy file [http://cfspreadsheet.leftbower.com:80/cfpoi.zip] to [/Users/jjackson/.CommandBox/server/87378098F0782EC1E8CA5FB73719A7A7-cb/lucee-4.5.2.018/WEB-INF/lucee-web/extensions/4C901E6B63FD9B49107D97B6E2C67D33/4.1.1.rep]
 	at java.net.SocketInputStream.socketRead0(Native Method):-2
 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116):116
 	at java.net.SocketInputStream.read(SocketInputStream.java:171):171
 	at java.net.SocketInputStream.read(SocketInputStream.java:141):141
 	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160):160
 	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84):84
 	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273):273
 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140):140
 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57):57
 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261):261
 	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283):283
 	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251):251
 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197):197
 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272):272
 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124):124
 	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685):685
 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487):487
 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882):882
 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82):82
 	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source):-1
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43):43
 	at java.lang.reflect.Method.invoke(Method.java:498):498
 	at lucee.commons.net.http.httpclient4.HTTPEngine4Impl.execute(HTTPEngine4Impl.java:423):423
 	at lucee.commons.net.http.httpclient4.HTTPEngine4Impl._invoke(HTTPEngine4Impl.java:253):253
 	at lucee.commons.net.http.httpclient4.HTTPEngine4Impl.get(HTTPEngine4Impl.java:113):113
 	at lucee.commons.net.http.HTTPEngine.get(HTTPEngine.java:86):86
 	at lucee.commons.io.res.type.http.HTTPResource.getHTTPResponse(HTTPResource.java:66):66
 	at lucee.commons.io.res.type.http.HTTPResource.getInputStream(HTTPResource.java:123):123
 	at lucee.commons.io.IOUtil.copy(IOUtil.java:167):167
 	at lucee.commons.io.res.util.ResourceSupport.copyTo(ResourceSupport.java:43):43
 	at lucee.commons.io.IOUtil.copy(IOUtil.java:119):119
 	at lucee.runtime.tag.FileTag.actionCopy(FileTag.java:517):517
 	at lucee.runtime.tag.FileTag.doStartTag(FileTag.java:359):359
 	at admin.extension.extensionmanager_cfc$cf.udfCall(/lucee-context-compiled/admin/extension/ExtensionManager.cfc:167):167
 	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:111):111
 	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:328):328
 	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:229):229
 	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:642):642
 	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:524):524
 	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1761):1761
 	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:742):742
 	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1590):1590
 	at admin.extension_applications_install1_cfm1518$cf.call(/lucee-context-compiled/admin/extension.applications.install1.cfm:47):47
 	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:951):951
 	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:855):855
 	at admin.extension_applications_cfm460$cf.call(/lucee-context-compiled/admin/extension.applications.cfm:98):98
 	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:951):951
 	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:855):855
 	at admin.web_cfm$cf.call(/lucee-context-compiled/admin/web.cfm:389):389
 	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:951):951
 	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:903):903
 	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:223):223
 	at lucee.runtime.listener.ModernAppListener.onRequest(ModernAppListener.java:101):101
 	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2262):2262
 	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2225):2225
 	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:456):456
 	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:47):47
 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790):790
 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85):85
 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129):129
 	at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47):47
 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61):61
 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131):131
 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84):84
 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62):62
 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36):36
 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131):131
 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57):57
 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43):43
 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46):46
 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64):64
 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60):60
 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77):77
 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43):43
 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43):43
 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43):43
 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292):292
 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81):81
 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138):138
 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135):135
 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48):48
 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43):43
 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272):272
 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81):81
 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104):104
 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211):211
 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809):809
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142):1142
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617):617
 	at java.lang.Thread.run(Thread.java:745):745
 
Timestamp	5/22/17 4:40:38 PM EDT
```

I tried again and got this pair of (non exception-dump) errors in the admin:

```
missing config file in extension package

error occured in /lucee-context-compiled/admin/extension.applications.install2.cfm:66
called by /lucee-context-compiled/admin/extension.applications.cfm:98
called by /lucee-context-compiled/admin/web.cfm:389
file or directory zip:///Users/jjackson/.CommandBox/server/87378098F0782EC1E8CA5FB73719A7A7-cb/lucee-4.5.2.018/WEB-INF/lucee-web/extensions/4C901E6B63FD9B49107D97B6E2C67D33/4.1.1.rep!/config.xml not exist

error occured in /lucee-context-compiled/admin/extension.applications.install2.cfm:110
called by /lucee-context-compiled/admin/extension.applications.cfm:98
called by /lucee-context-compiled/admin/web.cfm:389
```

I'll try again to see what happens.

**Comment by Leftbower** [comment]
Hmm... I just tried a fresh Commandbox install with `server start cfengine=lucee@4.5.5` I added the provider and it installed just fine.

I notice in your first post you mention you were running on Lucee 4.5.5.006 but the errors you posted seem to indicate lucee-4.5.2.018. Perhaps there is a Commandbox conflict of some sort?

**Comment by jamiejackson** [comment]
That was just a server I happened to have up at the time. I retried in the same server (removed provider, re-added, installed) and was successful. I think it was just a transient problem. I also was able to install in 4.5.5.006.

Thanks for the workaround!
